# Generated by Django 5.0.6 on 2024-06-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_material_current_stage_material_stages_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='stages_history',
        ),
        migrations.AlterField(
            model_name='material',
            name='current_stage',
            field=models.CharField(choices=[('RECEIVING', 'Recebimento'), ('WASHING', 'Lavagem'), ('PREPARATION', 'Preparo'), ('DISTRIBUTION', 'Distribuição')], default='RECEIVING', editable=False, max_length=50),
        ),
    ]
