# Generated by Django 5.0.6 on 2024-06-26 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_remove_stage_timestamp_material_stages_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='traceability',
        ),
    ]
