# Generated by Django 5.0.6 on 2024-06-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_delete_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='stages_history',
            field=models.TextField(blank=True, default='Recebimento'),
        ),
    ]
