from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import MaterialViewSet, FailureViewSet

# Create an instance of DefaultRouter
router = DefaultRouter()
# Register the MaterialViewSet with the router, creating URLs like /materials/
router.register(r'materials', MaterialViewSet)
# Register the FailureViewSet with the router, creating URLs like /failures/
router.register(r'failures', FailureViewSet)

# Include all URLs generated by the router in the urlpatterns
urlpatterns = [
    path('', include(router.urls)),
]