# Generated by Django 5.0.6 on 2024-06-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('INSTRUMENTALS', 'Instrumentais'), ('DISPOSABLES', 'Descartáveis'), ('CONSUMABLES', 'Materiais de Consumo'), ('TEXTILES', 'Artigos Têxteis'), ('IMPLANTS', 'Implantes'), ('GLASS_AND_PLASTICS', 'Vidros e Plásticos'), ('CLEANING_DISINFECTION', 'Materiais de Limpeza e Desinfecção'), ('PACKAGING', 'Embalagens'), ('EQUIPMENT_ACCESSORIES', 'Equipamentos e Acessórios')], max_length=50),
        ),
    ]
