# Generated by Django 5.0.6 on 2024-06-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_material_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='current_stage',
            field=models.CharField(choices=[('RECEIVING', 'Recebimento'), ('WASHING', 'Lavagem'), ('PREPARATION', 'Preparo'), ('DISTRIBUTION', 'Distribuição')], default='RECEIVING', max_length=50),
        ),
        migrations.AddField(
            model_name='material',
            name='stages_history',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('INSTRUMENTAIS', 'Instrumentais'), ('DESCARTAVEIS', 'Descartáveis'), ('MATERIAIS_DE_CONSUMO', 'Materiais de Consumo'), ('ARTIGOS_TEXTIL', 'Artigos Têxteis'), ('IMPLANTES', 'Implantes'), ('VIDROS_PLASTICOS', 'Vidros e Plásticos'), ('LIMPEZA_DESINFECCAO', 'Materiais de Limpeza e Desinfecção'), ('EMBALAGENS', 'Embalagens'), ('EQUIPAMENTOS_ACESSORIOS', 'Equipamentos e Acessórios')], max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='traceability',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
