# Generated by Django 5.0.6 on 2024-06-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alter_material_material_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='material',
            name='stages_history',
            field=models.TextField(default='Recebimento'),
        ),
    ]
