# Generated by Django 5.0.6 on 2024-06-26 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_alter_failure_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failures', to='materials.material'),
        ),
    ]
