# Generated by Django 5.0.6 on 2024-06-26 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_alter_failure_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='failure',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='stages_history',
            field=models.TextField(default='RECEIVING'),
        ),
    ]
