# Generated by Django 5.0.6 on 2024-06-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_alter_failure_description_alter_failure_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='failure',
            name='stage',
            field=models.CharField(choices=[('RECEIVING', 'Recebimento'), ('WASHING', 'Lavagem'), ('PREPARATION', 'Preparo'), ('DISTRIBUTION', 'Distribuição')], max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='current_stage',
            field=models.CharField(choices=[('RECEIVING', 'Recebimento'), ('WASHING', 'Lavagem'), ('PREPARATION', 'Preparo'), ('DISTRIBUTION', 'Distribuição')], default='RECEIVING', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='stages_history',
            field=models.TextField(),
        ),
    ]
