# Generated by Django 5.0.6 on 2024-06-26 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0012_alter_failure_description_alter_failure_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failures', to='materials.material'),
        ),
        migrations.AlterField(
            model_name='failure',
            name='stage',
            field=models.CharField(choices=[('RECEIVING', 'Recebimento'), ('WASHING', 'Lavagem'), ('PREPARATION', 'Preparo'), ('DISTRIBUTION', 'Distribuição')], max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='current_stage',
            field=models.CharField(choices=[('RECEIVING', 'Recebimento'), ('WASHING', 'Lavagem'), ('PREPARATION', 'Preparo'), ('DISTRIBUTION', 'Distribuição')], max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='stages_history',
            field=models.TextField(blank=True),
        ),
    ]
