# Generated by Django 5.0.6 on 2024-06-26 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0013_alter_failure_material_alter_failure_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material'),
        ),
    ]
