# Generated by Django 5.0.6 on 2024-06-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0014_alter_failure_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='stage',
            field=models.CharField(max_length=50),
        ),
    ]
