# Generated by Django 5.0.6 on 2024-06-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0015_alter_failure_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='stage',
            field=models.CharField(choices=[('RECEIVING', 'Recebimento'), ('WASHING', 'Lavagem'), ('PREPARATION', 'Preparo'), ('DISTRIBUTION', 'Distribuição')], max_length=50),
        ),
    ]
