# Generated by Django 5.0.6 on 2024-06-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0017_alter_material_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='stage',
            field=models.CharField(choices=[('RECEBIMENTO', 'Recebimento'), ('LAVAGEM', 'Lavagem'), ('PREPARO', 'Preparo'), ('DISTRIBUIÇÃO', 'Distribuição')], max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='current_stage',
            field=models.CharField(choices=[('RECEBIMENTO', 'Recebimento'), ('LAVAGEM', 'Lavagem'), ('PREPARO', 'Preparo'), ('DISTRIBUIÇÃO', 'Distribuição')], max_length=50),
        ),
    ]
